micronaut:
  application:
    name: scromania
  metrics:
    enabled: true
    export:
      azuremonitor:
        enabled: true
        instrumentationKey: 96a6b51d-4026-406c-b492-b6ec81b3df91
        step: PT1M
netty:
  default:
    allocator:
      max-order: 3
